services:
  db:
    image: postgres:16
    container_name: fantasy_postgres
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: fantasy_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"